# deployment.yaml definition 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-app
spec:
  replicas: 2
  selector:
    matcheLabels:
      app: gke-app
  template:
    metadata:
      labels:
        app: gke-app
    spec:
      containers:
        - name: gke-app
          image: ImageUrl
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
            